version: '3'
networks:
  - lottery-nets
services:
  lottery-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - lottery-nets
    ports:
      - "8888:8888"
    depends_on:
      - lottery-db

  lottery-db:
    image: postgres:latest
    networks:
      - lottery-nets
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lottery
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

