version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: lottery
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata:



#services:
#  postgres:
#    image: postgres:16.0
#    environment:
#      POSTGRES_DB: wallet
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#    volumes:
#      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
#    ports:
#      - "5432:5432"
#
#volumes:
#  pgdata:
